// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sftsrsjocrnxofvypsxv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNmdHNyc2pvY3JueG9mdnlwc3h2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2NzQwMTUsImV4cCI6MjA3MjI1MDAxNX0.Rr3XFhMH5fLjIWUYP7YjXLCUvtHurAq7It48of3mDFA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});